### ISSUE TITLE
autocomplete issues when using optional chaining

### ISSUE THREAD

**Issue by Cellule** [clinyong/vscode-css-modules#22]
Whenever I use optional chaining in my code, it seems the extension adds all the css class in the autocomplete choices.
Sometimes my css file will have a lot of classes adding a lot of them.

Example: 
```css
/* ReportingSummarySchedule.css */
.section {
  width: 33%;
}
.otherclass {}
```

![css-issue](https://user-images.githubusercontent.com/4157103/77563854-34508d00-6e98-11ea-91d5-b81a54591049.gif)
