### ISSUE TITLE
Support for nested classes (ampersand)

### ISSUE THREAD

**Issue by TuxGit** [clinyong/vscode-css-modules#31]
Add support for nested classes using with postcss, scss plugins.

Sometimes you need to separate the styles for the child container and add prefix for it.

Example
```css
.root { ... }

.label {
    font-size: 1rem;

    &_primary {
        color: green;
    }

    &_sizeSmall {
        font-size: 0.875rem;
    }
}
```

Expected result autocomplete
```
styles.label
       label_primary
       label_sizeSmall    
```

P.S. This case works in WebStorm
