### ISSUE TITLE
bracket syntax cannot jump

### ISSUE THREAD

**Issue by missop** [clinyong/vscode-css-modules#70]
```css
.help-me{
    color:red;
}
```
when i write,styles['help-me'],it can intelligent,but can not jump to the css class
